[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0f213a"
backgroundColor = "#f4f6f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f213a"
font = "sans serif"
